{% set name = "prettypyplot" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/prettypyplot-{{ version }}.tar.gz
  sha256: 54886789899ea9f6eb4d7427fc68042f80bf9679711e9b037c95ea424271e304

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - decorit >=0.2.0
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - prettypyplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/braniii/prettypyplot
  summary: Wrapper for matplotlib to generate publication-ready figures
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://braniii.gitlab.io/prettypyplot
  dev_url: https://gitlab.com/braniii/prettypyplot

extra:
  recipe-maintainers:
    - braniii
